server:
  port: 8001
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: liu1999.,
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka, http://eureka7002:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
