server:
  port: 8001
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_study?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #表示采样率，介于0~1之间，1表示采集全部
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
